### Тест запроса к Music.API через Gateway
GET https://localhost:7161/api/music/WeatherForecast
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiJhZGEwZTAxYi1hYzI4LTQwNDMtOWJjNi03M2E3MTZmOTI5YzUiLCJlbWFpbCI6InRvbW15aGFyZEBnbWFpbC5jb20iLCJEaXNwbGF5TmFtZSI6InN0cmluZyIsIm5iZiI6MTc3Njc4NTQxNywiZXhwIjoxNzc3MzkwMjE3LCJpYXQiOjE3NzY3ODU0MTcsImlzcyI6IkNvcGl1bWEuSWRlbnRpdHkiLCJhdWQiOiJDb3BpdW1hLkNsaWVudHMifQ.LYoA2maLGCiJdPGLmGgtFCXz5hcO4avipSVVSHH48yo